### ISSUE TITLE
Node V8.1.3

### ISSUE THREAD

**Issue by dev-clavis** [grant/Narrative#1]
At the time i want to run this app i get this error

```
app.configure(function(){
    ^

TypeError: app.configure is not a function
    at Object.<anonymous> (G:\Developper\Game Design\Narrative\app.js:21:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

Platform Win 10 x64
Node v8.1.3

**Comment by drusepth** [comment]
In order to get this running, you'll need to lock your `package-json` to the previous versions of express and mongodb that were used at the time of writing. Since they're locked to "at least" the versions in package.json, they're installing much more updated versions that have changed significantly, throwing this and other errors. 

You can get this running by changing
```
  "dependencies": {
    "express": ">= 3.4.0",
    "mongodb": ">= 1.3.19",
    "hbs": ">= 2.4.0"
  },
```
to
```
  "dependencies": {
    "express": "= 3.4.0",
    "mongodb": "^2.2.33",
    "hbs": ">= 2.4.0"
  },
```

Please note, however, that if you do so, there will be many security vulnerabilities that have since been fixed in these old versions, so you'll want to ensure you're patched up before exposing anything to the Big Bad Internet.

**Comment by drusepth** [comment]
This should be closeable now that #2 is merged. :)
